Name:           ros-indigo-pcan-topics
Version:        1.0.6
Release:        0%{?dist}
Summary:        ROS pcan_topics package

Group:          Development/Libraries
License:        GNU
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-indigo-catkin

%description
pcan topics is based on transmi- and receivetest. It consists of two nodes;
pcan_transmit and pcan_receive. The pcan_transmit is subscribed to the
pcan_transmit topic and sends a CAN message based on the string published. The
pcan_receive publishes incomming CAN messages on the pcan_receive topic in
string format.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Jan 12 2015 HJMeijdam <hendrik.meijdam@gmail.com> - 1.0.6-0
- Autogenerated by Bloom

